# Jekyll configuration for jharbieh.github.io
# Add your custom settings below

title: "Johnny Harbieh Coffee Shop IT WEBECCENTRIC Blog"
description: "Johnny Harbieh Coffee Shop IT WEBECCENTRIC Blog is about technology, music and career."
author: "Johnny Harbieh"
email: "johnny@webeccentric.com"
url: "https://jharbieh.github.io"
baseurl: ""
theme: minima
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
social:
  twitter: jharbieh
  github: jharbieh
  linkedin: jharbieh
plugins:
  - jekyll-seo-tag
  - jekyll-feed
