# Jekyll configuration for jharbieh.github.io
# Add your custom settings below

title: "Johnny Harbieh Coffee Shop IT WEBECCENTRIC Blog"
description: "Johnny Harbieh Coffee Shop IT WEBECCENTRIC Blog is about technology, music and career."
author: "Johnny Harbieh"
email: "johnny@webeccentric.com"
url: "https://jharbieh.github.io"
baseurl: ""
theme: minima
social:
  twitter: jharbieh
  github: jharbieh
  linkedin: jharbieh
plugins:
  - jekyll-seo-tag
  - jekyll-feed
